INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (1, 'GTX 1080 TI', 'Asus', 19299);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (2, 'GTX 1070', 'Asus', 15899);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (3, 'GTX 1060', 'Asus', 11589);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (4, 'RTX 3090 TUF', 'Asus', 120999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (5, 'RTX 3070', 'Asus', 52999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (6, 'RTX 3060', 'Asus', 42999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (7, 'GTX 1080', 'Gigabyte', 19999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (8, 'GTX 1080', 'MSI', 12999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (9, 'GTX 1080', 'Zotac', 12999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (10, 'RTX 3070', 'Ipason', 62999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (11, 'RTX 3060 OC', 'Ipason', 39999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (12, 'RTX 2060 OC', 'Ipason', 32999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (13, 'RTX 3060 OC', 'Zotac', 42999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (14, 'RTX 2060', 'Zotac',  32999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (15, 'RTX 3090', 'Ipason', 190999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (16, 'GTX 1060', 'Gigabyte', 12999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (17, 'GTX 1070', 'Gigabyte', 15999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (18, 'GTX 1080', 'EVGA', 17999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (19, 'GTX 1070', 'EVGA', 15999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (20, 'GTX 1060', 'EVGA', 10999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (21, 'GTX 1050', 'Ipason', 1050);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (22, 'GTX 1050', 'PNY', 1050);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (23, 'GTX 1050', 'Zotac', 1050);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (24, 'GTX 1050', 'EVGA', 1050);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (25, 'GTX 1050', 'Asus', 1050);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (26, 'GTX 750 TI', 'ASUS', 599);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (27, 'GT 130', 'ASUS', 1050);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (28, 'RX 470 OC', 'MSI', 41000);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (29, 'RX Vega 64', 'MSI', 59999);
INSERT INTO [dbo].[product_tbl] (prod_id, name, brand, msrp) VALUES (30, 'GTX 1050 TI', 'PNY', 34195);

INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (1, 1, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (2, 2, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (3, 3, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (4, 4, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (5, 5, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (6, 6, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (7, 7, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (8, 8, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (9, 9, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (10, 10, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (11, 11, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (12, 12, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (13, 13, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (14, 14, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (15, 15, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (16, 16, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (17, 17, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (18, 18, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (19, 19, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (20, 20, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (21, 21, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (22, 22, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (23, 23, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (24, 24, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (25, 25, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (26, 26, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (27, 27, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (28, 28, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (29, 29, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (30, 30, 20, 'Good');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (31, 1, 5, 'Defective');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (32, 2, 2, 'Defective');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (33, 3, 3, 'Defective');
INSERT INTO [dbo].[product_status_tbl] (status_id, prod_id, qty, status) VALUES (33, 5, 6, 'Defective');